//
//  PokemonDetailsPresenter.swift
//  Viper-v2-Demo
//
//  Created by Donik Vrsnak on 4/11/18.
//  Copyright (c) 2018 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PokemonDetailsPresenter {

    // MARK: - Private properties -

    private unowned var _view: PokemonDetailsViewInterface
    private var _interactor: PokemonDetailsInteractorInterface
    private var _wireframe: PokemonDetailsWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: PokemonDetailsWireframeInterface, view: PokemonDetailsViewInterface, interactor: PokemonDetailsInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension PokemonDetailsPresenter: PokemonDetailsPresenterInterface {
}
