//
//  RegisterInteractor.swift
//  Viper-v2-Demo
//
//  Created by Donik Vrsnak on 5/30/18.
//  Copyright (c) 2018 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class RegisterInteractor {
}

// MARK: - Extensions -

extension RegisterInteractor: RegisterInteractorInterface {
}
