//
//  RegisterViewController.swift
//  Viper-v2-Demo
//
//  Created by Donik Vrsnak on 5/30/18.
//  Copyright (c) 2018 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RegisterViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: RegisterPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension RegisterViewController: RegisterViewInterface {
}
