//
//  RegisterPresenter.swift
//  Viper-v2-Demo
//
//  Created by Donik Vrsnak on 5/30/18.
//  Copyright (c) 2018 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RegisterPresenter {

    // MARK: - Private properties -

    private unowned var _view: RegisterViewInterface
    private var _interactor: RegisterInteractorInterface
    private var _wireframe: RegisterWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: RegisterWireframeInterface, view: RegisterViewInterface, interactor: RegisterInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension RegisterPresenter: RegisterPresenterInterface {
    func didSelectCloseAction() {
        _wireframe.dismiss(animated: true)
    }
}
