//
//  RegisterInterfaces.swift
//  Viper-v2-Demo
//
//  Created by Donik Vrsnak on 5/30/18.
//  Copyright (c) 2018 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum RegisterNavigationOption {
}

protocol RegisterWireframeInterface: WireframeInterface {
    func navigate(to option: RegisterNavigationOption)
}

protocol RegisterViewInterface: ViewInterface {
}

protocol RegisterPresenterInterface: PresenterInterface {
    func didSelectCloseAction()
}

protocol RegisterInteractorInterface: InteractorInterface {
}
