//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ___VARIABLE_moduleName___NavigationOption {
}

protocol ___VARIABLE_moduleName___WireframeInterface: WireframeInterface {
    func navigate(to option: ___VARIABLE_moduleName___NavigationOption)
}

protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
}

protocol ___VARIABLE_moduleName___InteractorInterface: InteractorInterface {
}
