//___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ___VARIABLE_moduleName___WireframeInterface: WireframeInterface {
}

protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
}

protocol ___VARIABLE_moduleName___FormatterInterface: FormatterInterface {
}

protocol ___VARIABLE_moduleName___InteractorInterface: InteractorInterface {
}
