//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum ___VARIABLE_moduleName___NavigationOption {
}

protocol ___VARIABLE_moduleName___WireframeInterface: WireframeInterface {
    func navigate(using option: Driver<___VARIABLE_moduleName___NavigationOption>)
    func navigate(to option: ___VARIABLE_moduleName___NavigationOption)
}

protocol ___VARIABLE_moduleName___ViewInterface: ViewInterface {
}

protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
    func setup(with output: ___VARIABLE_moduleName___ViewOutput) -> ___VARIABLE_moduleName___ViewInput
}

protocol ___VARIABLE_moduleName___InteractorInterface: InteractorInterface {
}

struct ___VARIABLE_moduleName___Input {
}

struct ___VARIABLE_moduleName___ViewInput {
}

struct ___VARIABLE_moduleName___ViewOutput {
}