//
//  DetailsWireframe.swift
//  Viper-Demo
//
//  Created by Zvonimir Medak on 07.10.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class DetailsWireframe: BaseWireframe<DetailsViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Details", bundle: nil)

    // MARK: - Module setup -

    init(showId: String) {
        let moduleViewController = storyboard.instantiateViewController(ofType: DetailsViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = DetailsFormatter()
        let interactor = DetailsInteractor()
        let presenter = DetailsPresenter(
            view: moduleViewController,
            formatter: formatter,
            interactor: interactor,
            wireframe: self,
            showId: showId
        )
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailsWireframe: DetailsWireframeInterface {
}
