//
//  DetailsViewController.swift
//  Viper-Demo
//
//  Created by Zvonimir Medak on 07.10.2021..
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class DetailsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: DetailsPresenterInterface!

    // MARK: - Private properties -

    @IBOutlet var tableView: UITableView!
    private let disposeBag = DisposeBag()
    private lazy var tableDataSource: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: tableView)
    }()
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension DetailsViewController: DetailsViewInterface {
}

private extension DetailsViewController {

    func setupView() {
        let output = Details.ViewOutput()

        let input = presenter.configure(with: output)
        handle(title: input.events.title)
        handle(items: input.models.sections)
    }

    func handle(title: Signal<String>) {
        title
            .emit(to: self.rx.title)
            .disposed(by: disposeBag)
    }

    func handle(items: Driver<[TableSectionItem]>) {
        items
            .drive(tableDataSource.rx.sections)
            .disposed(by: disposeBag)
    }

}
