//
//  ShowDetailsPresenter.swift
//  Viper-Demo
//
//  Created by Zvonimir Medak on 07.10.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class ShowDetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: ShowDetailsViewInterface
    private let formatter: ShowDetailsFormatterInterface
    private let interactor: ShowDetailsInteractorInterface
    private let wireframe: ShowDetailsWireframeInterface

    private let showId: String
    private let disposeBag: DisposeBag
    // MARK: - Lifecycle -

    init(
        view: ShowDetailsViewInterface,
        formatter: ShowDetailsFormatterInterface,
        interactor: ShowDetailsInteractorInterface,
        wireframe: ShowDetailsWireframeInterface,
        showId: String
    ) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe

        self.disposeBag = DisposeBag()
        self.showId = showId
    }
}

// MARK: - Extensions -

extension ShowDetailsPresenter: ShowDetailsPresenterInterface {

    func configure(with output: ShowDetails.ViewOutput) -> ShowDetails.ViewInput {
        let titleRelay = PublishRelay<String>()
        let formatterInput = ShowDetails.FormatterInput(models: handleInitialLoad(titleRelay: titleRelay))

        let formatterOutput = formatter.format(for: formatterInput)

        return ShowDetails.ViewInput(
            models: formatterOutput,
            events: ShowDetailsEvents(title: titleRelay.asSignal())
        )
    }

}

private extension ShowDetailsPresenter {

    func handleInitialLoad(titleRelay: PublishRelay<String>) -> Driver<(Show, [Review])> {
        return Single.zip(
            interactor.getShowDetails(for: showId),
            interactor.getAllReviews(for: showId)
        )
            .do(onSuccess: { [unowned view] show, _ in
                titleRelay.accept(show.title)
                view.hideProgressHUD()
            }, onError: { [unowned self] error in
                view.hideProgressHUD()
                showDetailsError(error)
            }, onSubscribe: { [unowned view] in
                view.showProgressHUD()
            })
            .asDriver(onErrorDriveWith: .empty())
    }

    func showDetailsError(_ error: Error) {
        wireframe.showAlert(with: "Error", message: error.localizedDescription)
    }
}
