//
//  ShowDetailsWireframe.swift
//  Viper-Demo
//
//  Created by Zvonimir Medak on 07.10.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ShowDetailsWireframe: BaseWireframe<ShowDetailsViewController> {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "ShowDetails", bundle: nil)

    // MARK: - Module setup -

    init(showId: String) {
        let moduleViewController = storyboard.instantiateViewController(ofType: ShowDetailsViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = ShowDetailsFormatter()
        let interactor = ShowDetailsInteractor()
        let presenter = ShowDetailsPresenter(
            view: moduleViewController,
            formatter: formatter,
            interactor: interactor,
            wireframe: self,
            showId: showId
        )
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ShowDetailsWireframe: ShowDetailsWireframeInterface {
}
