//
//  ShowDetailsFormatter.swift
//  Viper-Demo
//
//  Created by Zvonimir Medak on 07.10.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ShowDetailsFormatter {
}

// MARK: - Extensions -

extension ShowDetailsFormatter: ShowDetailsFormatterInterface {

    func format(for input: ShowDetails.FormatterInput) -> ShowDetails.FormatterOutput {

        return ShowDetails.FormatterOutput(sections: handle(input.models))
    }

}

private extension ShowDetailsFormatter {
    func handle(_ items: Driver<(Show, [Review])>) -> Driver<[TableSectionItem]> {
        return items
            .map { [unowned self] in
                createShowDetailsSectionItems(items: $0)
            }
    }

    func createShowDetailsSectionItems(items: (show: Show, reviews: [Review])) -> [ShowDetailsSection] {
        var showDetailsItems: [ShowDetailsItem] = []
        showDetailsItems.append(contentsOf: createMandatoryItems(items.show))
        showDetailsItems.append(contentsOf: createReviewSection(with: items.show, items.reviews))
        return [ShowDetailsSection(items: showDetailsItems)]
    }

    func createMandatoryItems(_ show: Show) -> [ShowDetailsItem] {
        var showDetailsItems: [ShowDetailsItem] = []
        showDetailsItems.append(
            ShowDetailsItem(
                model: ShowWithReviews(
                    show: show,
                    review: nil
                ),
                type: .image
            )
        )
        showDetailsItems.append(
            ShowDetailsItem(
                model: ShowWithReviews(
                    show: show,
                    review: nil
                ),
                type: .description
            )
        )
        showDetailsItems.append(
            ShowDetailsItem(
                model: ShowWithReviews(
                    show: nil,
                    review: nil
                ),
                type: .reviewsTitle
            )
        )
        return showDetailsItems
    }

    func createReviewSection(with show: Show, _ reviews: [Review]) -> [ShowDetailsItem] {
        var showDetailsItems: [ShowDetailsItem] = []
        guard reviews.isEmpty else {
            showDetailsItems.append(
                ShowDetailsItem(
                    model: ShowWithReviews(
                        show: show,
                        review: nil
                    ),
                    type: .averageRating
                )
            )
            reviews.forEach { review in
                showDetailsItems.append(
                    ShowDetailsItem(
                        model: ShowWithReviews(
                            show: nil,
                            review: review
                        ),
                        type: .review
                    )
                )
            }
            showDetailsItems.append(
                ShowDetailsItem(
                    model: ShowWithReviews(
                        show: show,
                        review: nil
                    ),
                    type: .addReview
                )
            )
            return showDetailsItems
        }
        showDetailsItems.append(
            ShowDetailsItem(
                model: ShowWithReviews(
                    show: show,
                    review: nil
                ),
                type: .noReviews
            )
        )
        return showDetailsItems
    }
}
