//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___./Users/azmimuhammad/Documents/helper/iOS-VIPER-Xcode-Templates/Templates/VIPER Templates/Module.xctemplate/NoneInteractor/___FILEBASENAME___Presenter.swift
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator/Users/azmimuhammad/Documents/helper/iOS-VIPER-Xcode-Templates/Templates/VIPER Templates/Module.xctemplate/NoneInteractorAndFormatter/___FILEBASENAME___Presenter.swift
//

import Foundation

final class ___VARIABLE_moduleName___Presenter {

    // MARK: - Private properties -

    private weak var view: ___VARIABLE_moduleName___ViewInterface?
    private let interactor: ___VARIABLE_moduleName___InteractorInterface
    private let wireframe: ___VARIABLE_moduleName___WireframeInterface

    // MARK: - Lifecycle -

    init(view: ___VARIABLE_moduleName___ViewInterface, interactor: ___VARIABLE_moduleName___InteractorInterface, wireframe: ___VARIABLE_moduleName___WireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Presenter: ___VARIABLE_moduleName___PresenterInterface {
}
