import UIKit

// THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
// swiftlint:disable file_length type_body_length line_length superfluous_disable_command
extension UIImage {
	enum ViperDemo {}
}

extension UIImage.ViperDemo {

	static var hidePassword: UIImage { return UIImage(named: "hide_password", in: .main, compatibleWith: nil)! }
	static var logo: UIImage { return UIImage(named: "logo", in: .main, compatibleWith: nil)! }
	static var checkboxUnchecked: UIImage { return UIImage(named: "checkbox_unchecked", in: .main, compatibleWith: nil)! }
	static var checkboxChecked: UIImage { return UIImage(named: "checkbox_checked", in: .main, compatibleWith: nil)! }
	static var showPassword: UIImage { return UIImage(named: "show_password", in: .main, compatibleWith: nil)! }
	static var background: UIImage { return UIImage(named: "background", in: .main, compatibleWith: nil)! }
}
