//
//  HomeInterfaces.swift
//  Viper-Demo
//
//  Created by Zvonimir Medak on 06.10.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
    func navigateToLogin()
    func navigateToShowDetails(id: String)
}

protocol HomeViewInterface: ViewInterface {
    func reloadData()
}

protocol HomePresenterInterface: PresenterInterface {
    var numberOfItems: Int { get }
    
    func item(at indexPath: IndexPath) -> Show
    func itemSelected(at indexPath: IndexPath)
    func logout()
    func loadShows()
}

protocol HomeInteractorInterface: InteractorInterface {
    func getShows(_ completion: @escaping ((Result<[Show], Error>) -> Void))
    func logout()
}
