//___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

protocol ___VARIABLE_moduleName___WireframeInterface: WireframeInterface {
}

protocol ___VARIABLE_moduleName___InteractorInterface: InteractorInterface {
}
