//___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ___VARIABLE_moduleName___Interactor {
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorInterface {
}
