//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ___FILEBASENAMEASIDENTIFIER___Presenter {

    // MARK: - Private properties -

    fileprivate weak var _view: ___FILEBASENAMEASIDENTIFIER___ViewInterface?
    fileprivate var _interactor: ___FILEBASENAMEASIDENTIFIER___InteractorInterface
    fileprivate var _wireframe: ___FILEBASENAMEASIDENTIFIER___WireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: ___FILEBASENAMEASIDENTIFIER___WireframeInterface, view: ___FILEBASENAMEASIDENTIFIER___ViewInterface, interactor: ___FILEBASENAMEASIDENTIFIER___InteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }

}

// MARK: - Extensions -

extension ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___PresenterInterface {
}
