//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ___FILEBASENAMEASIDENTIFIER___NavigationOption {
}

protocol ___FILEBASENAMEASIDENTIFIER___WireframeInterface: WireframeInterface {
    func navigate(to option: ___FILEBASENAMEASIDENTIFIER___NavigationOption)
}

protocol ___FILEBASENAMEASIDENTIFIER___ViewInterface: ViewInterface {
}

protocol ___FILEBASENAMEASIDENTIFIER___PresenterInterface: PresenterInterface {
}

protocol ___FILEBASENAMEASIDENTIFIER___InteractorInterface: InteractorInterface {
}
