//___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import SwiftUI

struct ___VARIABLE_moduleName___View: View {

    @ObservedObject var presenter: ___VARIABLE_moduleName___Presenter

    var body: some View {
        Text(/*@START_MENU_TOKEN@*/"Hello, World!"/*@END_MENU_TOKEN@*/)
    }
}
