//
//  RxPokemonDetailsInteractor.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 27.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class RxPokemonDetailsInteractor {
}

// MARK: - Extensions -

extension RxPokemonDetailsInteractor: RxPokemonDetailsInteractorInterface {
}
