//
//  RxPokemonDetailsFormatter.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 27.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RxPokemonDetailsFormatter {
}

// MARK: - Extensions -

extension RxPokemonDetailsFormatter: RxPokemonDetailsFormatterInterface {

    func format(for input: RxPokemonDetails.FormatterInput) -> RxPokemonDetails.FormatterOutput {
        return RxPokemonDetails.FormatterOutput()
    }

}
