//
//  RxPokemonDetailsPresenter.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 27.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class RxPokemonDetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: RxPokemonDetailsViewInterface
    private let formatter: RxPokemonDetailsFormatterInterface
    private let interactor: RxPokemonDetailsInteractorInterface
    private let wireframe: RxPokemonDetailsWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: RxPokemonDetailsViewInterface,
        formatter: RxPokemonDetailsFormatterInterface,
        interactor: RxPokemonDetailsInteractorInterface,
        wireframe: RxPokemonDetailsWireframeInterface
    ) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RxPokemonDetailsPresenter: RxPokemonDetailsPresenterInterface {

    func configure(with output: RxPokemonDetails.ViewOutput) -> RxPokemonDetails.ViewInput {

        let formatterInput = RxPokemonDetails.FormatterInput()

        let formatterOutput = formatter.format(for: formatterInput)

        return RxPokemonDetails.ViewInput(models: formatterOutput)
    }

}
