//
//  RxPokemonDetailsPresenter.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 27.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class RxPokemonDetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: RxPokemonDetailsViewInterface
    private let formatter: RxPokemonDetailsFormatterInterface
    private let interactor: RxPokemonDetailsInteractorInterface
    private let wireframe: RxPokemonDetailsWireframeInterface

    private let pokemon: Pokemon

    // MARK: - Lifecycle -

    init(
        view: RxPokemonDetailsViewInterface,
        formatter: RxPokemonDetailsFormatterInterface,
        interactor: RxPokemonDetailsInteractorInterface,
        wireframe: RxPokemonDetailsWireframeInterface,
        pokemon: Pokemon
    ) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe

        self.pokemon = pokemon
    }
}

// MARK: - Extensions -

extension RxPokemonDetailsPresenter: RxPokemonDetailsPresenterInterface {

    func configure(with output: RxPokemonDetails.ViewOutput) -> RxPokemonDetails.ViewInput {
        let pokemon = Driver.just(pokemon)
        let formatterInput = RxPokemonDetails.FormatterInput(models: pokemon)

        let formatterOutput = formatter.format(for: formatterInput)

        let title = Driver.just(self.pokemon.title).compactMap { $0 }
        let imageURL = Signal.just(self.pokemon.imageURL).compactMap { $0 }
        return RxPokemonDetails.ViewInput(models: formatterOutput, events: RxPokemonDetailsEvent(title: title, imageURL: imageURL))
    }

}
