//
//  RxPokemonDetailsWireframe.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 27.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RxPokemonDetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "RxPokemonDetails", bundle: nil)

    // MARK: - Module setup -

    init(pokemon: Pokemon) {
        let moduleViewController = storyboard.instantiateViewController(ofType: RxPokemonDetailsViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = RxPokemonDetailsFormatter()
        let interactor = RxPokemonDetailsInteractor()
        let presenter = RxPokemonDetailsPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self, pokemon: pokemon)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension RxPokemonDetailsWireframe: RxPokemonDetailsWireframeInterface {
}
