//
//  RxPokemonDetailsViewController.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 27.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RxPokemonDetailsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: RxPokemonDetailsPresenterInterface!

    // MARK: - Private properties -

    @IBOutlet private weak var tableView: UITableView!
    @IBOutlet private weak var headerImageView: UIImageView!
    private lazy var tableDataSource: TableDataSourceDelegate = {
        return TableDataSourceDelegate(tableView: tableView)
    }()

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension RxPokemonDetailsViewController: RxPokemonDetailsViewInterface {
}

private extension RxPokemonDetailsViewController {

    func setupView() {
        let output = RxPokemonDetails.ViewOutput()

        let input = presenter.configure(with: output)
        initializeTableView(with: input.models.sections)
    }

    func initializeTableView(with sections: Driver<[TableSectionItem]>) {
        sections
            .drive(tableDataSource.rx.sections)
            .disposed(by: disposeBag)
    }
}
