//
//  RxPokemonDetailsViewController.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 27.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RxPokemonDetailsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: RxPokemonDetailsPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension RxPokemonDetailsViewController: RxPokemonDetailsViewInterface {
}

private extension RxPokemonDetailsViewController {

    func setupView() {
        let output = RxPokemonDetails.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
