//
//  RxLoginInterfaces.swift
//  Viper-v2-Demo
//
//  Created by Zvonimir Medak on 22.09.2021..
//  Copyright (c) 2021 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa



protocol RxLoginWireframeInterface: WireframeInterface {
    func navigate(to option: LoginNavigationOption)
}

protocol RxLoginViewInterface: ViewInterface {
}

protocol RxLoginPresenterInterface: PresenterInterface {
    func configure(with output: RxLogin.ViewOutput) -> RxLogin.ViewInput
}

protocol RxLoginInteractorInterface: InteractorInterface {
    func login(with email: String, _ password: String) -> Single<User>
}

enum RxLogin {

    struct ViewOutput {
        let actions: RxLoginActions
    }

    struct ViewInput {
        let events: RxLoginEvents
    }

}

struct RxLoginActions {
    let email: Driver<String?>
    let password: Driver<String?>
    let login: Signal<Void>
    let register: Signal<Void>
}
struct RxLoginEvents {
    let buttonAvailability: Driver<Bool>
}
