//
//  PokemonDetailsInterfaces.swift
//  Viper-v2-Demo
//
//  Created by Donik Vrsnak on 4/11/18.
//  Copyright (c) 2018 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum PokemonDetailsNavigationOption {
}

protocol PokemonDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: PokemonDetailsNavigationOption)
}

protocol PokemonDetailsViewInterface: ViewInterface {
    func setViewTitle(_ title: String?)
    func setHeaderImage(with url: URL?)
    func reloadData()
}

protocol PokemonDetailsPresenterInterface: PresenterInterface {
    func numberOfSections() -> Int
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> PokemonDetailsItem
}

protocol PokemonDetailsInteractorInterface: InteractorInterface {
}

// MARK: Table view items

enum PokemonDetailsItem {
    case description(PokemonDetailsDescriptionItemInterface)
    case characteristics(PokemonDetailsCharacteristicsItemInterface)
    case comment(PokemonDetailsCommentItemInterface)
}

protocol PokemonDetailsDescriptionItemInterface {
    var pokemonName: String? { get }
    var pokemonDescription: String? { get }
}

protocol PokemonDetailsCharacteristicsItemInterface {
    var height: Float? { get }
    var weight: Float? { get }
    var gender: String? { get }
}

protocol PokemonDetailsCommentItemInterface {
    var author: String? { get }
    var date: Date? { get }
    var text: String? { get }
}
