//
//  PokemonDetailsInteractor.swift
//  Viper-v2-Demo
//
//  Created by Donik Vrsnak on 4/11/18.
//  Copyright (c) 2018 Infinum. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PokemonDetailsInteractor {
}

// MARK: - Extensions -

extension PokemonDetailsInteractor: PokemonDetailsInteractorInterface {
}
