//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ___VARIABLE_moduleName___Presenter: ObservableObject {
        
    final class Navigation: ObservableObject {

    }

    // MARK: - Private properties -

    private let navigation: Navigation

    // MARK: - Lifecycle -

    init(navigation: Navigation) {
        self.navigation = navigation
    }
}
