//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import SwiftUI

struct ___VARIABLE_moduleName___Wireframe: View {

    @StateObject var navigation = ___VARIABLE_moduleName___Presenter.Navigation()

    var body: some View {
        let presenter = ___VARIABLE_moduleName___Presenter(navigation: navigation)
        
        ___VARIABLE_moduleName___View(presenter: presenter)
    }
}