platform :ios, '9.0'

def testing_pods
  pod 'Quick', '~> 1.1'
  pod 'Nimble', '~> 6.1'
  pod 'OHHTTPStubs', '~> 6.0'
  pod 'OHHTTPStubs/Swift'
end

def app_pods
  pod 'Japx/CodableAlamofire'
  pod 'SVProgressHUD', '~> 2.1'
  pod 'AlamofireImage', '~> 3.2'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.1'
end

target 'Viper-v2-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Viper-v2-Demo
  app_pods

  target 'Viper-v2-DemoTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'Viper-v2-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

end
