//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ___VARIABLE_moduleName___Interactor {
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorInterface {
}
