import UIKit

// THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
// swiftlint:disable file_length type_body_length line_length superfluous_disable_command
extension UIColor {
	enum Viperv4Demo {}
}

extension UIColor.Viperv4Demo {

	static var accentColor: UIColor { return UIColor(named: "AccentColor", in: .main, compatibleWith: nil)! }
}
