import UIKit

// THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
// swiftlint:disable file_length type_body_length line_length superfluous_disable_command
extension UIImage {
	enum Viperv4Demo {}
}

extension UIImage.Viperv4Demo {

	static var logo: UIImage { return UIImage(named: "logo", in: .main, compatibleWith: nil)! }
	static var background: UIImage { return UIImage(named: "background", in: .main, compatibleWith: nil)! }
}
