//___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ___VARIABLE_moduleName___Formatter {
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Formatter: ___VARIABLE_moduleName___FormatterInterface {
}
