//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ___VARIABLE_moduleName___WireframeInterface: WireframeInterface {
}

protocol ___VARIABLE_moduleName___PresenterInterface: PresenterInterface {
}

protocol ___VARIABLE_moduleName___FormatterInterface: FormatterInterface {
    func format(for input: ___VARIABLE_moduleName___.FormatterInput) -> ___VARIABLE_moduleName___.FormatterOutput
}

protocol ___VARIABLE_moduleName___InteractorInterface: InteractorInterface {
}

enum ___VARIABLE_moduleName___ {

    struct FormatterInput {
    }

    struct FormatterOutput {
    }

}
