//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ___VARIABLE_moduleName___Formatter {
}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Formatter: ___VARIABLE_moduleName___FormatterInterface {

    func format(for input: ___VARIABLE_moduleName___.FormatterInput) -> ___VARIABLE_moduleName___.FormatterOutput {
        return ___VARIABLE_moduleName___.FormatterOutput()
    }

}
