//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import SwiftUI

struct ___VARIABLE_moduleName___View: View {

    @ObservedObject var presenter: ___VARIABLE_moduleName___Presenter

    var body: some View {
        Text(/*@START_MENU_TOKEN@*/"Hello, World!"/*@END_MENU_TOKEN@*/)
    }
}

// MARK: - Previews -

#if DEBUG
struct ___VARIABLE_moduleName___View_Previews: PreviewProvider {

    class ___VARIABLE_moduleName___WireframeMock: ___VARIABLE_moduleName___WireframeInterface {
    }

    static var previews: some View {
        let wireframe = ___VARIABLE_moduleName___WireframeMock()

        let presenter = ___VARIABLE_moduleName___Presenter(wireframe: wireframe)

        return ___VARIABLE_moduleName___View(presenter: presenter)
    }
}
#endif
