//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit


final class ___VARIABLE_moduleName___Wireframe: BaseWireframe<LazyHostingViewController<___VARIABLE_moduleName___View>> {

    final class ___VARIABLE_moduleName___Wireframe: BaseWireframe<> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = LazyHostingViewController<___VARIABLE_moduleName___View>()
        super.init(viewController: moduleViewController)

        let formatter = ___VARIABLE_moduleName___Formatter()
        let interactor = ___VARIABLE_moduleName___Interactor()
        let presenter = ___VARIABLE_moduleName___Presenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.rootView = ___VARIABLE_moduleName___View(presenter: presenter)
    }

}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Wireframe: ___VARIABLE_moduleName___WireframeInterface {
}
