//___FILEHEADER___
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ___VARIABLE_moduleName___Wireframe: BaseWireframe<LazyHostingViewController<___VARIABLE_moduleName___View>> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = LazyHostingViewController<___VARIABLE_moduleName___View>()
        super.init(viewController: moduleViewController)

        let presenter = ___VARIABLE_moduleName___Presenter(wireframe: self)
        moduleViewController.rootView = ___VARIABLE_moduleName___View(presenter: presenter)
    }

}

// MARK: - Extensions -

extension ___VARIABLE_moduleName___Wireframe: ___VARIABLE_moduleName___WireframeInterface {
}
